### ISSUE TITLE
Fix SQL Data Access Layer

### ISSUE THREAD

**Issue by canna002** [bkinney91/InventoryManagement#12]

**Comment by canna002** [comment]
The database was given an empty path, fixed below:

sqlDAL\* sqlDAL::getInstance(QString sqlPath)
{
    if(!objSqlDAL && !sqlPath.isEmpty())
        objSqlDAL = new sqlDAL(sqlPath);

```
return objSqlDAL;
```

}

**Comment by bkinney91** [comment]
Are you getting a build error with the latest source?
loginDialog.obj:-1: error: LNK2019: unresolved external symbol "public:
class QSqlQueryModel \* __cdecl Inventory::queryInventory(void)"
(?queryInventory@Inventory@@QEAAPEAVQSqlQueryModel@@XZ) referenced in
function "private: void __cdecl LoginDialog::on_loginButton_clicked(void)"
(?on_loginButton_clicked@LoginDialog@@AEAAXXZ)

**Comment by canna002** [comment]
No.build errors for me. Thats weird.

**Comment by bkinney91** [comment]
I've had too many problems with QT

**Comment by canna002** [comment]
I was able to compile and run it. I can show you tomorow in class.

**Comment by bkinney91** [comment]
Alright, not 100% sure I'll be there but I'll try

**Comment by canna002** [comment]
Maybe its the config of the project. I can try to fix it in class.

**Comment by canna002** [comment]
Kay
