### ISSUE TITLE
SQL connection

### ISSUE THREAD

**Issue by bkinney91** [bkinney91/InventoryManagement#13]
"QSqlQuery::exec: database not open"

When executing function in the dashboard DAL there is an issue with the connection to the database. At any given time some of the functions can access the database fine and return values properly, but some return false on "sqlDB->query(mtdSaleValue) && sqlDB->result()". It is arbitrary which ones fail. Can you try running the code and see if you have the same issue? I wonder if the fact that the database is singleton has to do with this.

**Comment by bkinney91** [comment]
When I debug it, it seems most of them work fine, which leads me to believe that it is a timing issue of some sort?

**Comment by canna002** [comment]
Can you send me what you have done so far? So I can check out the problem. You don't have to commit the changes just yet. You can zip the folder and email it to me.

**Comment by canna002** [comment]
Never mind you committed it.

**Comment by bkinney91** [comment]
Let me know what you find, I'll keep working on it

**Comment by canna002** [comment]
Okay will do.

**Comment by canna002** [comment]
That is the issue, I had the same problem and I fixed it by removing it from the constructor and having a method called displayInventory() which is called inside the loginDialog.

HomePage::HomePage(QWidget\* parent) : QMainWindow(parent),
    uiHomePage(new Ui::HomePage)
{
    uiHomePage->setupUi(this);

```
QString sqlPath = qApp->applicationDirPath() + "/sql/db.sqlite3";
sqlDB = sqlDAL::getInstance(sqlPath);
Dashboard* dashboard = Dashboard::getDashboardInstance();
uiHomePage->OrderDisplay->setText(dashboard->mtdOrdersCost);
uiHomePage->SalesDisplay->setText(dashboard->mtdOrdersCost);
uiHomePage->OverheadCostDisplay->setText(dashboard->overheadCost);
uiHomePage->OverheadValueDisplay->setText(dashboard->overheadValue);
uiHomePage->OverheadNetDisplay->setText(dashboard->overheadNet);
```

## }

// Copy this style
void HomePage::displayInventory(QSqlQueryModel\* inventoryTable)
{
    uiHomePage->inventoryTable->setModel(inventoryTable);
    uiHomePage->inventoryTable->resizeRowsToContents();
    uiHomePage->inventoryTable->resizeColumnsToContents();
}

// Inside loginDialog.cpp 
if(sqlDB->query(sqlQuery) && sqlDB->result())
    {
        inventory = new Inventory(sqlPath);
        QSqlQueryModel\* inventoryTable = inventory->queryInventory();

```
    uiLogin->loginResult->setText("[+]Login successful");

    homePage.show();
    homePage.displayInventory(inventoryTable);
    homePage.yourDisplayMethod(); // Create a similar method as above.
    this->close();
}
```

If you need any clarification, let me know.

**Comment by bkinney91** [comment]
Haha that's exactly what I was doing to test. Glad it works. Did you commit?

**Comment by canna002** [comment]
No commit, I am actually working on my architecture hw and theory of computing project. Can you fix it? It's not hard.

**Comment by bkinney91** [comment]
Yeah I'll commit, I got it

**Comment by canna002** [comment]
Okay thanks man, once I finish my homework, I can start working on this again.

**Comment by bkinney91** [comment]
No worries man, study what you need to

**Comment by bkinney91** [comment]
Fixed
